### ISSUE TITLE
Make Nub Corporate the face of Nub Bank (the default landing)

### ISSUE THREAD

**Issue by Padanub** [Nub-International-Group/ModelWorld-Bank#183]
https://github.com/Padanub/Nub-Bank-Corporate, let me know if its a shit site and needs more work

**Comment by adjwood** [comment]
@strideynet This would be like a 10 minute job, no?

**Comment by strideynet** [comment]
no.

**Comment by adjwood** [comment]
what would make it take so long? Is google cloud a bitch for that?

**Comment by strideynet** [comment]
Uh, setting up CI/CD pipelines for it so I don't have to do it manually everytime nub makes a change? Probably just like 45 minutes including setting up the subdomain and the storage bucket to serve it out of.

**Comment by adjwood** [comment]
Ahh fair enough - didn't consider the need to update the page 😛
