### ISSUE TITLE
Model-Mili does not have an account

### ISSUE THREAD

**Issue by Padanub** [Nub-International-Group/ModelWorld-Bank#192]
I've checked their account and its definitely on the right username, he tried clearing his cache on firefox but still gets

![image](https://user-images.githubusercontent.com/20230725/77864548-19c43e00-7221-11ea-93a3-1190da03ca2e.png)

**Comment by Padanub** [comment]
Mili says it works on chrome but still not on firefox.. weird

**Comment by adjwood** [comment]
is his account "Model-mili" and not "model-mili"? E.G is it case sensitive? Perhaps Chrome is ignoring case sensitivity but Firefox is not, and that is what is going on.

Also get him to check he is logged into the correct account on https://reddit.com

**Comment by adjwood** [comment]
Also login works fine for me on Firefox - my guess he is logged in to a different reddit account.

**Comment by strideynet** [comment]
@Padanub is this resolved?
