### ISSUE TITLE
Would it be a good idea to add a "Refund" button somewhere?

### ISSUE THREAD

**Issue by adjwood** [Nub-International-Group/ModelWorld-Bank#199]
Right now, if someone mistakanly sends money and ask for a refund, the recieving party loses out on money due to the TX fee. Would it be a good idea to introduce a "Refund" button for Transactions so the TX fee is ignored? And maybe refund the Original Senders TX fee as well (or not, gotta keep the lights on I guess)

**Comment by Padanub** [comment]
Like the idea but want to think through the solution some more before we move ahead

**Comment by Padanub** [comment]
Users need to speak to the bank, just like IRL. we will refund the tx fee manually
